[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/template',
    'runtime/deskchains',

    "modules/*",
	"modules/evm-utiltity/macro",
	# "inspect",
	"primitives",
]
